# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class I18n < Formula
  desc "A tool to extract translations from CSV file and append to the strings resources in your Android project"
  homepage "https://github.com/master-g/i18n"
  version "0.1.5"
  license "Apache License"

  on_macos do
    on_intel do
      url "https://github.com/master-g/i18n/releases/download/v0.1.5/i18n_0.1.5_darwin_amd64.zip"
      sha256 "a469ac58c8890f1c9704ab090fd30f24dc3958908914545fe6e06cd3dfdb9c0e"

      def install
        bin.install "i18n"
      end
    end
    on_arm do
      url "https://github.com/master-g/i18n/releases/download/v0.1.5/i18n_0.1.5_darwin_arm64.zip"
      sha256 "a0e28767d264002521fb93294063d01d43280028f6ee6a2094b47305f8d20f59"

      def install
        bin.install "i18n"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/master-g/i18n/releases/download/v0.1.5/i18n_0.1.5_linux_amd64.zip"
        sha256 "5ebac95fe3b6417ae11b5d9eda39817307fc1650e69a966d77f36271a8b4fe8c"

        def install
          bin.install "i18n"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/master-g/i18n/releases/download/v0.1.5/i18n_0.1.5_linux_arm64.zip"
        sha256 "aa8dc3b46e4e4eee73e737a23fa31095326d404eee2be781c821aec6ccfd2706"

        def install
          bin.install "i18n"
        end
      end
    end
  end

  test do
    system "#{bin}/i18n version"
  end
end
