# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class I18n < Formula
  desc "A tool to extract translations from CSV file and append to the strings resources in your Android project"
  homepage "https://github.com/master-g/i18n"
  version "0.1.1"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/master-g/i18n/releases/download/v0.1.1/i18n_0.1.1_darwin_arm64.zip"
      sha256 "0cb4ffee2b181d471999ab92f6aad7cb2538a7a62d8f7271bea8442711990fc6"

      def install
        bin.install "i18n"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/i18n/releases/download/v0.1.1/i18n_0.1.1_darwin_amd64.zip"
      sha256 "4e974e279297e45335fe4de92c2ef245c34751d44a1ed00be4da62563142d020"

      def install
        bin.install "i18n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/master-g/i18n/releases/download/v0.1.1/i18n_0.1.1_linux_arm64.zip"
      sha256 "c59380f1a4e6fa51af7099cd72eb51d536f1188be05b9d32a6cdad237efb9180"

      def install
        bin.install "i18n"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/i18n/releases/download/v0.1.1/i18n_0.1.1_linux_amd64.zip"
      sha256 "58bfa268b59ae14afcadc31d0ade227589362dc85838f3811ff46da9db791584"

      def install
        bin.install "i18n"
      end
    end
  end

  test do
    system "#{bin}/i18n version"
  end
end
