# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class I18n < Formula
  desc "A tool to extract translations from CSV file and append to the strings resources in your Android project"
  homepage "https://github.com/master-g/i18n"
  version "0.1.4"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/master-g/i18n/releases/download/v0.1.4/i18n_0.1.4_darwin_arm64.zip"
      sha256 "2d4fb33c0dacc3c36532c088a62bd33eec259e3bb9750d90dc34929d4c6e6827"

      def install
        bin.install "i18n"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/i18n/releases/download/v0.1.4/i18n_0.1.4_darwin_amd64.zip"
      sha256 "e97ae638ffecd1dd5c8292af0f929b36c4d11a2bd88649a7c6f266d9040ab8ee"

      def install
        bin.install "i18n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/master-g/i18n/releases/download/v0.1.4/i18n_0.1.4_linux_arm64.zip"
      sha256 "cf91c9f3efff123013f45e0b543f7689df3e7249b3983ce5c6ae55a36a0ec06d"

      def install
        bin.install "i18n"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/i18n/releases/download/v0.1.4/i18n_0.1.4_linux_amd64.zip"
      sha256 "731d7888ae8fa7caaebcb2e90ceaea26b5d29b0e74c4027c9e44fc9432621b74"

      def install
        bin.install "i18n"
      end
    end
  end

  test do
    system "#{bin}/i18n version"
  end
end
