# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenBean < Formula
  desc "Java Value Object Generator Plugin For Protobuf"
  homepage "https://github.com/master-g/protoc-gen-bean"
  version "0.2.4"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/master-g/protoc-gen-bean/releases/download/v0.2.4/protoc-gen-bean_0.2.4_darwin_arm64.zip"
      sha256 "287113cf3bb60ae3aa91a4a40d5df64d96ab8674c1e97c9187949fb6208aeb2b"

      def install
        bin.install "protoc-gen-bean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/protoc-gen-bean/releases/download/v0.2.4/protoc-gen-bean_0.2.4_darwin_amd64.zip"
      sha256 "6f3f5cdbdcda4918119bed2cdde67034a4b875a62d05712bc999bf025398731a"

      def install
        bin.install "protoc-gen-bean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/master-g/protoc-gen-bean/releases/download/v0.2.4/protoc-gen-bean_0.2.4_linux_arm64.zip"
      sha256 "7f82d62d86bd4af176ae933495798dc3b97c0cb79986d5e76547f171976a9728"

      def install
        bin.install "protoc-gen-bean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/protoc-gen-bean/releases/download/v0.2.4/protoc-gen-bean_0.2.4_linux_amd64.zip"
      sha256 "0f8d09a8f1154a0c05716211f444a3589cd6375eb8a201929366fee2abf310eb"

      def install
        bin.install "protoc-gen-bean"
      end
    end
  end

  test do
    system "#{bin}/protoc-gen-bean -h"
  end
end
