# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProtocGenBean < Formula
  desc "Java Value Object Generator Plugin For Protobuf"
  homepage "https://github.com/master-g/protoc-gen-bean"
  version "0.2.3"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/master-g/protoc-gen-bean/releases/download/v0.2.3/protoc-gen-bean_0.2.3_darwin_arm64.zip"
      sha256 "07fec944a137862392966b9d3b18778c73da55551b37be7b856b70c5c39d4d18"

      def install
        bin.install "protoc-gen-bean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/protoc-gen-bean/releases/download/v0.2.3/protoc-gen-bean_0.2.3_darwin_amd64.zip"
      sha256 "0ce106d01a538101c0d3f5c1880070eeaef0d9284efe86895016bedbf75cd63a"

      def install
        bin.install "protoc-gen-bean"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/master-g/protoc-gen-bean/releases/download/v0.2.3/protoc-gen-bean_0.2.3_linux_arm64.zip"
      sha256 "2dfe0895e61c1bb854ea378fb59be640566261efc9da53722a5cf3eb05352e8d"

      def install
        bin.install "protoc-gen-bean"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/protoc-gen-bean/releases/download/v0.2.3/protoc-gen-bean_0.2.3_linux_amd64.zip"
      sha256 "a6e2932fbbb9bbfd78d71f44fb904b42bb733a476bd1ffc2ddb598e3c8b0db28"

      def install
        bin.install "protoc-gen-bean"
      end
    end
  end

  test do
    system "#{bin}/protoc-gen-bean -h"
  end
end
