# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timber < Formula
  desc "A tool to extract translations from CSV file and append to the strings resources in your Android project"
  homepage "https://github.com/master-g/timber"
  version "0.0.5"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/master-g/timber/releases/download/v0.0.5/timber_0.0.5_darwin_arm64.zip"
      sha256 "8ca9f89e5b237e8e6e6d86dad975b1ed54acdec0b768cd799812536e3e40eb65"

      def install
        bin.install "timber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/timber/releases/download/v0.0.5/timber_0.0.5_darwin_amd64.zip"
      sha256 "957ecd3f9f53a78bcb40ece4e0a6da41f3fa40f900a898b3b4e3d177a5b5c0a4"

      def install
        bin.install "timber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/master-g/timber/releases/download/v0.0.5/timber_0.0.5_linux_arm64.zip"
      sha256 "1b659140ce77f97182b855f40d5f0e7789fcb418ecc60e6850922a580d5eca50"

      def install
        bin.install "timber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/timber/releases/download/v0.0.5/timber_0.0.5_linux_amd64.zip"
      sha256 "63c90c051a548997fd2e97a2b2be8bad76b1ca9af73873b2aa8d6a1a9d093a69"

      def install
        bin.install "timber"
      end
    end
  end

  test do
    system "#{bin}/timber version"
  end
end
