# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timber < Formula
  desc "A tool to extract translations from CSV file and append to the strings resources in your Android project"
  homepage "https://github.com/master-g/timber"
  version "0.0.1"
  license "Apache License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/master-g/timber/releases/download/v0.0.1/timber_0.0.1_darwin_arm64.zip"
      sha256 "b5fd69758cc36b72eb7d8297dfb9ea13e2d1843f90ffa3ca3367f6b5b6eeb01d"

      def install
        bin.install "timber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/timber/releases/download/v0.0.1/timber_0.0.1_darwin_amd64.zip"
      sha256 "e3b4ef09455b73859548559a7fe082506ed5393841709567001b2c923635102f"

      def install
        bin.install "timber"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/master-g/timber/releases/download/v0.0.1/timber_0.0.1_linux_arm64.zip"
      sha256 "1e4cf6abe8a09cd2c14a5f3c9662b5499458663469d089bf43f0df4acaaf559b"

      def install
        bin.install "timber"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/master-g/timber/releases/download/v0.0.1/timber_0.0.1_linux_amd64.zip"
      sha256 "7ec009dd450e6d1295fb5848ca4fece15796aad5db52292fbb067fc594e5dd02"

      def install
        bin.install "timber"
      end
    end
  end

  test do
    system "#{bin}/timber version"
  end
end
